//
//  BWEncryption.h
//
//  Copyright © 2022 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#import <Foundation/Foundation.h>
#import <OpenSSL/OpenSSL.h>
#import <CommonCrypto/CommonHMAC.h>
#import "BWEncryptionOutput.h"

NS_ASSUME_NONNULL_BEGIN

@interface BWEncryption : NSObject

// Returns public key base64 encoded
- (nullable NSString *)generateKeys;

// Set shared key from previous session
- (BOOL)setSharedKey:(NSData *)sharedKey;

// Decrypts shared key using the private key generated by previous method
- (nullable NSString *)decryptSharedKey:(NSString *)sharedKey;

// Encrypts data using the shared key decrypted in previous method
- (nullable BWEncryptionOutput *)encryptData:(NSData *)data;

// Decrypts data using the shared key
- (NSData *)decryptData:(NSData *)data andIv:(NSData *)ivData;

// Computes Hmac used for comparison after receiving of messages
- (NSData *)computeHmac:(NSData *)data iv:(NSData *)ivData;

// Cleans public, private and shared key
- (void)cleanKeys;

@end

NS_ASSUME_NONNULL_END
