
disabled_rules:
  - trailing_whitespace
  - no_space_in_method_call
  - multiple_closures_with_trailing_closure
  - block_based_kvo
  - compiler_protocol_init

# Rule Config
line_length: 150
identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 60
type_name:
  min_length: 3
  max_length:
    warning: 80
    error: 100
file_length:
  warning: 700
  error: 1200
nesting:
  type_level: 2

# General Config
excluded:
  - DuckDuckGo/Common/Localizables/UserText.swift

