export const MSG_NAME_SET_VALUES = 'setUserValues'
export const MSG_NAME_READ_VALUES = 'readUserValues'
export const MSG_NAME_OPEN_PLAYER = 'openDuckPlayer'
export const MSG_NAME_PUSH_DATA = 'onUserValuesChanged'
export const MSG_NAME_PIXEL = 'sendDuckPlayerPixel'
export const MSG_NAME_PROXY_INCOMING = 'ddg-serp-yt'
export const MSG_NAME_PROXY_RESPONSE = 'ddg-serp-yt-response'
