name: Map GitHub username to Asana user id 
description: |
  Maps a DDG GitHub username to the equivalent DDG Asana user id.
inputs:
  github-user:
    description: "The GitHub username"
    required: true
    type: string
outputs:
  asana-user-id:
    description: "The Asana user id for the correspondent GitHub username"
    value: ${{ steps.map-github-to-asana-user.outputs.asana_user_id }}
runs:
  using: "composite"
  steps:
    - id: map-github-to-asana-user
      shell: bash
      run: |
        echo asana_user_id=$(jq -r .${{ github.event.requested_reviewer.login }} < ${{ github.action_path }}/user_ids.json) >> "$GITHUB_OUTPUT"
