data:
  # yq -o=j | sed -E 's/\\n( *)([^\\n])/\2/g'
  html_text: |
    <body>
      <h2>Internal release build ${TAG} ready ✅</h2>
      <ul>
        <li>📥 DMG is available from <a href='${DMG_URL}'>${DMG_URL}</a>.
          <ul>
            <li>If this is a subsequent internal release (started by calling <em>Bump Internal Release</em> workflow), the DMG will be automatically published to Sparkle in a few minutes. Sit tight.</li>
          </ul></li>
        </li>
        <li>🏷️ Repository is tagged with <code>${TAG}</code> tag.</li>
        <li>🚢 GitHub <a href='${RELEASE_URL}'>${TAG} pre-release</a> is created.</li>
        <li>🔱 <code>${BRANCH}</code> branch has been successfully merged to <code>${BASE_BRANCH}</code>.</li>
      </ul>

      🔗 Workflow URL: <a href='${WORKFLOW_URL}'>${WORKFLOW_URL}</a>.
    </body>
