data:
  # yq -o=j | sed -E 's/\\n( *)([^\\n])/\2/g'
  html_text: |
    <body>
      <h2>[ACTION NEEDED] Public release ${TAG} tagged</h2>
      <ul>
        <li>🏷️ Repository is tagged with <code>${TAG}</code> tag.</li>
        <li>🚢 GitHub <a href='${RELEASE_URL}'>${TAG} release</a> is created.</li>
        <li><b>❗️ Deleting <code>${BRANCH}</code> failed.</b>
          <ul>
            <li><a data-asana-gid='${ASSIGNEE_ID}'/>, please proceed with deleting the branch manually <a data-asana-gid='${TASK_ID}' data-asana-dynamic='false'>according to instructions</a>.</li>
          </ul></li>
      </ul>

      🔗 Workflow URL: <a href='${WORKFLOW_URL}'>${WORKFLOW_URL}</a>.
    </body>
