name: Add a Message to Asana Release Automation Task
description: Adds a comment about release progress to the Asana release task's "Automation" subtask
inputs:
  access-token:
    description: "Asana access token"
    required: true
    type: string
  task-url:
    description: "Asana release task URL"
    required: false
    type: string
  comment:
    description: "Comment to add to the Asana task"
    required: false
    type: string
  template-name:
    description: |
      Name of a template file (without extension) for the comment, relative to 'templates'
      subdirectory of the 'asana-add-comment' action.
      The file is processed by envsubst before being sent to Asana.
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - id: get-automation-subtask
      shell: bash
      env:
        ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
      run: bundle exec fastlane run asana_get_release_automation_subtask_id task_url:"${{ inputs.task-url }}"

    - id: get-asana-user-id
      shell: bash
      if: github.event_name != 'schedule'
      run: bundle exec fastlane run asana_get_user_id_for_github_handle github_handle:"${{ github.actor }}"

    - id: add-colaborator
      shell: bash
      env:
        ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
        ASSIGNEE_ID: ${{ steps.get-asana-user-id.outputs.asana_user_id || steps.get-automation-subtask.outputs.asana_assignee_id }}
        TASK_ID: ${{ steps.get-automation-subtask.outputs.asana_automation_task_id }}
      run: |
        return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/addFollowers" \
          -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
          -H 'content-type: application/json' \
          --write-out '%{http_code}' \
          --output /dev/null \
          -d "{ \"data\": { \"followers\": [ \"${ASSIGNEE_ID}\" ] } }")

        if [ $return_code -ne 200 ]; then
          echo "::error::Failed to add a collaborator to the Asana task"
          exit 1
        fi

    - id: add-comment
      uses: ./.github/actions/asana-add-comment
      with:
        access-token: ${{ inputs.access-token }}
        task-id: ${{ steps.get-automation-subtask.outputs.asana_automation_task_id }}
        comment: ${{ inputs.comment }}
        template-name: ${{ inputs.template-name }}
