name: Create Asana PR subtask
description: |
  Creates a PR subtask and assigns it to the team member in charge of the GitHub review.
  If the PR subtask already exists, it ensures the reviewer is assigned and the task is not marked 'completed'.
inputs:
  access-token:
    description: "Asana access token"
    required: true
    type: string
  asana-task-id:
    description: "Asana Task ID for the PR"
    required: string
    type: string
  github-reviewer-user:
    description: "GitHub username for the requested reviewer"
    required: true
    type: string
  github-pr-url:
    description: "GitHub URL for the opened PR"
    required: true
    type: string
runs:
  using: "composite"
  steps:
      - name: Get Asana user ID
        id: get-asana-user-id
        uses: duckduckgo/apple-infra/actions/asana-get-user-id-for-github-handle@main
        with:
          access-token: ${{ inputs.access-token }}
          github-handle: ${{ inputs.github-reviewer-user }}
        
      - name: "Create PR Subtask"
        shell: bash
        env:
          ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
        run: |
          ${{ github.action_path }}/asana-create-pr-subtask.sh ${{ inputs.asana-task-id }} ${{ steps.get-asana-user-id.outputs.user-id }} ${{ inputs.github-pr-url }}
