data:
  name: Merge ${BRANCH} to ${BASE_BRANCH}
  assignee: "${ASSIGNEE_ID}"
  html_notes: |
    <body>
      The <code>${TAG}</code> release has been successfully tagged and published in GitHub releases, 
      but merging to <code>${BASE_BRANCH}</code> failed. Please resolve conflicts and merge <code>${BRANCH}</code> to <code>${BASE_BRANCH}</code> manually.


      Issue the following git commands:
      <ul>
        <li><code>git fetch origin</code></li>
        <li><code>git checkout ${BRANCH}</code> switch to the release branch</li>
        <li><code>git pull origin ${BRANCH}</code> pull latest changes</li>
        <li><code>git checkout ${BASE_BRANCH}</code> switch to ${BASE_BRANCH}</li>
        <li><code>git pull origin ${BASE_BRANCH}</code> pull the latest code</li>
        <li><code>git merge ${BRANCH}</code>
          <ul>
            <li>resolve conflicts as needed</li>
          </ul></li>
        <li><code>git push origin ${BASE_BRANCH}</code> push merged branch</li>
      </ul>
      Complete this task when ready and proceed with testing the build.


      🔗 Workflow URL: <a href='${WORKFLOW_URL}'>${WORKFLOW_URL}</a>.
    </body>
