data:
  name: Tag ${BRANCH} branch, delete it, and create GitHub release
  assignee: "${ASSIGNEE_ID}"
  html_notes: |
    <body>
      Failed to tag the release with <code>${TAG}</code> tag.

      Please follow instructions below to tag the branch, make GitHub release and delete the release branch manually.
      <ul>
        <li>If the tag has already been created, please proceed with creating GitHub release and deleting the branch.</li>
        <li>If both tag and GitHub release have already been created, please close this task already.</li>
      </ul>

      Issue the following git commands to tag the release and delete the branch:
      <ul>
        <li><code>git fetch origin</code></li>
        <li><code>git checkout ${BRANCH}</code> switch to the release branch</li>
        <li><code>git pull origin ${BRANCH}</code> pull latest changes</li>
        <li><code>git tag ${TAG}</code> tag the release</li>
        <li><code>git push origin ${TAG}</code> push the tag</li>
        <li><code>git checkout ${BASE_BRANCH}</code> switch to ${BASE_BRANCH}</li>
        <li><code>git push origin --delete ${BRANCH}</code> delete the release branch</li>
      </ul>

      To create GitHub release:
      <ul>
        <li>Set up GH CLI if you haven't yet: <a data-asana-gid='1203791243007683'/></li>
        <li>Run the following command:
        <ul>
          <li><code>gh release create ${TAG} --generate-notes --latest --notes-start-tag ${LAST_RELEASE_TAG}</code></li>
        </ul></li>
      </ul>

      Complete this task when ready.


      🔗 Workflow URL: <a href='${WORKFLOW_URL}'>${WORKFLOW_URL}</a>.
    </body>
