name: Upload file to Asana
description: Uploads a file to an Asana task
inputs:
  access-token:
    description: "Asana access token"
    required: true
    type: string
  file-name:
    description: "Name of the uploaded file"
    required: true
    type: string
  task-url:
    description: "Asana task URL"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - run: |
        task_url_regex='^https://app.asana.com/[0-9]/[0-9]*/([0-9]*)/f$'
        if [[ "${{ inputs.task-url }}" =~ ${task_url_regex} ]]; then
          echo "task_id=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        else
          echo "::error::Asana Task URL has incorrect format (attempted to match ${task_url_regex})."
        fi
      shell: bash
    - run: |
          curl -s "https://app.asana.com/api/1.0/tasks/${task_id}/attachments" \
            -H "Authorization: Bearer ${{ inputs.access-token }}" \
            --form "file=@${{ inputs.file-name }}"
      shell: bash
