name: Upload file to Asana
description: Uploads a file to an Asana task
inputs:
  access-token:
    description: "Asana access token"
    required: true
    type: string
  file-name:
    description: "Name of the uploaded file"
    required: true
    type: string
  task-id:
    description: "Asana task ID"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - run: |
        curl -fLSs "https://app.asana.com/api/1.0/tasks/${{ inputs.task-id }}/attachments" \
          -H "Authorization: Bearer ${{ inputs.access-token }}" \
          --form "file=@${{ inputs.file-name }}"
      shell: bash
