name: Create Asana Task on Test Failure

on:
  workflow_run:
    workflows:
      - PR Checks
    types:
      - completed
jobs:
  asana:
    name: Create Asana Task
    runs-on: ubuntu-latest
    needs:
      - swiftlint
    if: ${{ github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.head_branch == 'bunn/gha-test' }}
    steps:
      - uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: "1201037661562251"
          asana-task-name: GH Workflow Failure
          action: create-asana-task
          asana-task-description: Tests after merging have failed. See
            https://github.com/duckduckgo/macos-browser/actions/runs/${{
            github.run_id }}