name: Create Asana Task on Test Failure

on:
  pull_request:
    types:
      - edited

jobs:
  create_asana_task:
    runs-on: ubuntu-latest

    steps:
      - uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: '1201037661562251'
          asana-task-name: GH Workflow Failure
          action: 'create-asana-task'
          asana-task-description: Checks failed