name: Create Asana Task on Test Failure

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      description:
        required: true
        type: string
      project-id:
        required: true
        type: string
jobs:
  asana:
    name: Create Asana Task
    runs-on: ubuntu-latest

    steps:
      - uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: inputs.project-id
          asana-task-name: inputs.title
          action: create-asana-task
          asana-task-description: inputs.description