name: Create Asana Task on Test Failure

on:
  pull_request:
    types:
      - closed

jobs:
  create_asana_task:
    runs-on: ubuntu-latest

    steps:
      - uses: malmstein/github-asana-action@v0.7.0
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: '1201037661562251'
          asana-task-name: 'Test Asana Integration'
          action: 'create-asana-issue-task'