name: Create Asana Task on Test Failure

on:
  pull_request:
    types:
      - edited

jobs:
  create_asana_task:
    runs-on: ubuntu-latest

    steps:
      - uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: '1201037661562251'
          action: 'create-asana-issue-task'

      - name: Ensure Action sees template files
        uses: actions/checkout@v2

      - name: Render response template
        id: render_template
        uses: chuhlomin/render-template@v1.7
        with:
          template: .github/pr-reply-template.md

      - name: Add comment to Pull Request
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: '.github/pr-reply-template.md'