name: Migration Test - Asana Get Automation Subtask ID

on: 
  push:
  workflow_dispatch:

jobs:
  test:

    name: Test

    runs-on: macos-14

    steps:
 
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up fastlane
      run: bundle install

    - name: Test asana_log_message (mimicks build_appstore.yml/Report success and build_notarized.yml/Report success)
      env:
        DSYM_S3_PATH: "example/path"
        TAG: "1.2.3"
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
      run: |
        bundle exec fastlane run asana_log_message \
          task_url:"https://app.asana.com/0/1201392122292466/1208233977568870/f" \
          template_name:"debug-symbols-uploaded" \
          github_handle:"${{ github.actor }}"

    - name: Test asana_log_message (mimicks publish_dmg_release/yml/Report status)
      if: always()
      env:
        ANNOUNCEMENT_TASK_ID: "1208233977568874"
        ASSIGNEE_ID: "1201392122268514"
        TASK_ID: "1208233977568870"
        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        bundle exec fastlane run asana_log_message \
          task_url:"https://app.asana.com/0/1201392122292466/1208233977568870/f" \
          template_name:"validate-check-for-updates-public" \
          github_handle:"${{ github.actor }}"