name: Migration Test - Asana Upload

on: 
  push:
  workflow_dispatch:

jobs:
  test:

    name: Test

    runs-on: macos-14

    steps:
 
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up fastlane
      run: bundle install

    - name: Test asana_upload
      env:
        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
      run: |
        bundle exec fastlane run asana_upload \
          file_name:"Gemfile" \
          task_id:"${{ 1208189657535242 }}" 